### PR TITLE
Add try/catch to ProxyHandler handle() method

### PR DESCRIPTION
**Pull request by adrianluisgonzalez**
Add try/catch to ProxyHandler handle() method and call msg.fail() if there is an exception so caller receives the error message rather than a ReplyFailure.TIMEOUT exception.

### CODE REVIEW

**Comment by cescoffier** [comment]
Loos good to me.

I'm wondering if the error code -1 should be specified somewhere (was already there before).

**Comment by vietj** [comment]
would you mind redoing a PR without reformatting the source code ? that does not ease review.

**Comment by adrianluisgonzalez** [comment]
@vietj, happy to change formatting, but which reformatting are you referring to?  Since I added the try/catch block, I indented the code inside the block two spaces.  Is that what you are referring to?

**Comment by vietj** [comment]
I'm taking in fact of the extra unnecessary white space included in the PR \n and ' ' chars

**Comment by adrianluisgonzalez** [comment]
My mistake on the space between the variable name and the `:` in the `for` loops, I see that is the standard formatting in the vert.x project and I have removed that.  

However the line break between methods is standard no?  Is it that you disagree with the change or would prefer a separate PR with the formatting changes?

**Comment by adrianluisgonzalez** [comment]
I have removed formatting changes and opened a separate PR #20 .

One question is whether the catch should throw the exception or just log it.

**Pull request merged**
