### PR TITLE
Fix #28

### LINKED ISSUE #28: Be able to use a Enum type as a result
Documentation says that an Enum can be passed as a parameter to a method but not for a result.

I tried an got a IllegalArgumentException:

    No message codec for type: class com.example.MyEnum

Any chance we can change that? Or there is a technical reason behind this choice ?

I'm running Vert.x 3.1.

Thanks!

### PR DESCRIPTION
**Pull request by cescoffier**
Add support for enum in results

### CODE REVIEW

**Comment by vietj** [comment]
just looking at it, it seems that we don't handle the case with an enum annotated with @VertxGen. So we need to support it too.

**Comment by cescoffier** [comment]
You mean something like this:

```
@VertxGen
public enum SomeVertxEnum {
  FOO, BAR, WIBBLE
}
```

This does not change anything (it is handled as an enum).

**Comment by cescoffier** [comment]
Actually, it does not generate anything for such enum.

**Comment by cescoffier** [comment]
I've added a unit test with an enum annotated with @VertxGen.

**Comment by vietj** [comment]
looks good to me

**Pull request merged**
